# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cadd293b201ace5400a79b7a0eafbb7c90573d9dc28b51b5f41939ef3bb0edbe723d19590d7434e2e751accb03d1ee81c7733ee558b001159641c13724021715

test:
  secret_key_base: 7dda3751b5ea570bd06632f42468d11d13a4a41bbd9381be2da8da071e91456867b8219246da1ef8bed3f60d1151e7c733c664134f2dd6ef2aa3fef36d85e944

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
